const serviceActionType = {
    ALL_SERVICE_REQUEST : "ALL_SERVICE_REQUEST",
    ALL_SERVICE_SUCCESS : "ALL_SERVICE_SUCCESS",
    ALL_SERVICE_FAIL : "ALL_SERVICE_FAIL",

    NEW_SERVICE_REQUEST : "NEW_SERVICE_REQUEST",
    NEW_SERVICE_SUCCESS : "NEW_SERVICE_SUCCESS",
    NEW_SERVICE_FAIL : "NEW_SERVICE_FAIL",

    SERVICE_DETAILS_REQUEST : "SERVICE_DETAILS_REQUEST",
    SERVICE_DETAILS_SUCCESS : "SERVICE_DETAILS_SUCCESS",
    SERVICE_DETAILS_FAIL : "SERVICE_DETAILS_FAIL",

    UPDATE_SERVICE_SUCCESS : "UPDATE_SERVICE_SUCCESS",
    UPDATE_SERVICE_FAIL : "UPDATE_SERVICE_FAIL",

    NEW_DEVICE_REQUEST : "NEW_DEVICE_REQUEST",
    NEW_DEVICE_SUCCESS : "NEW_DEVICE_SUCCESS",
    NEW_DEVICE_RESET : "NEW_DEVICE_RESET",
    NEW_DEVICE_FAIL : "NEW_DEVICE_FAIL",

    UPDATE_DEVICE_REQUEST : "UPDATE_DEVICE_REQUEST",
    UPDATE_DEVICE_SUCCESS : "UPDATE_DEVICE_SUCCESS",
    UPDATE_DEVICE_FAIL : "UPDATE_DEVICE_FAIL",

    DELETE_DEVICE_SUCCESS : "DELETE_DEVICE_SUCCESS",
    DELETE_DEVICE_FAIL : "DELETE_DEVICE_FAIL",
}

export default serviceActionType