const userActionType = {
    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL : "USER_LOGIN_FAIL",

    USER_REGISTRATION_REQUEST : "USER_REGISTRATION_REQUEST",
    USER_REGISTRATION_SUCCESS : "USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAIL : "USER_REGISTRATION_FAIL",

    USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_FAIL : "USER_LOGOUT_FAIL",

    UPDATE_PASSWORD_REQUEST : "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS : "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAIL : "UPDATE_PASSWORD_FAIL",

    ALL_USER_REQUEST : "ALL_USER_REQUEST",
    ALL_USER_SUCCESS : "ALL_USER_SUCCESS",
    ALL_USER_FAIL : "ALL_USER_FAIL",

    USER_DETAIL_REQUEST : "USER_DETAIL_REQUEST",
    USER_DETAIL_SUCCESS : "USER_DETAIL_SUCCESS",
    USER_DETAIL_FAIL : "USER_DETAIL_FAIL"

}

export default userActionType