const vendorActionType = {
    ALL_VENDORS_REQUEST : "ALL_VENDORS_REQUEST",
    ALL_VENDORS_SUCCESS : "ALL_VENDORS_SUCCESS",
    ALL_VENDORS_FAIL : "ALL_VENDORS_FAIL",

    ADD_VENDOR_REQUEST : "ADD_VENDOR_REQUEST",
    ADD_VENDOR_SUCCESS : "ADD_VENDOR_SUCCESS",
    ADD_VENDOR_FAIL : "ADD_VENDOR_FAIL",

    VENDOR_DETAILS_REQUEST : "VENDOR_DETAILS_REQUEST",
    VENDOR_DETAILS_SUCCESS : "VENDOR_DETAILS_SUCCESS",
    VENDOR_DETAILS_FAIL : "VENDOR_DETAILS_FAIL",

    UPDATE_VENDOR_REQUEST : "UPDATE_VENDOR_REQUEST",
    UPDATE_VENDOR_SUCCESS : "UPDATE_VENDOR_SUCCESS",
    UPDATE_VENDOR_FAIL : "UPDATE_VENDOR_FAIL",

}

export default vendorActionType